### ISSUE TITLE
NoMethodError: private method `read_attribute_for_serialization + attributes property in AttrJson:Model should be HashWithIndifferentAccess

### ISSUE THREAD

**Issue by bbarberBPL** [jrochkind/attr_json#73] opened 2019-10-15 18:44 UTC
Using
ruby 2.5.7
'rails',  '5.2.3'
'attr_json',  '0.7.0'
'active_model_serializers', '0.10.0'
'rails', ' 5.2.3'

Give the following context I have two `attr_json` models that inherit from a `FieldSet` Class

```
   class FieldSet
      include AttrJson::Model
    end

   class TitleSet < FieldSet
      attr_json :primary, Title.to_type, store_key: 'primary'
      attr_json :other, Title.to_type, store_key: 'other', array: true, default: []

      validates :primary, presence: true
    end

    class Title < FieldSet
      attr_json :label, :string
      attr_json :subtitle, :string
      attr_json :display, :string
      attr_json :display_label, :string
      attr_json :usage, :string
      attr_json :supplied, :boolean
      attr_json :language, :string
      attr_json :type, :string
      attr_json :authority_code, :string
      attr_json :id_from_auth, :string
      attr_json :part_number, :string
      attr_json :part_name, :string
    end

```
The `TitlelSet` model is a jsonb column on my `Descriptive` model

When using the following two serializers
```
class TitleSerializer < ActiveModel::Serializer
       attributes :label, :usage, :display, :subtitle, :language
  end


    class TitleSetSerializer < ActiveModel::Serializer
      attribute :primary do
        TitleSerializer.new(object.primary).as_json
      end

      attribute :other do
        ActiveModelSerializers::SerializableResource.new(object.other, each_serializer: TitleSerializer adapter: :attributes).as_json
      end
    end
```
  In the Descriptive Serializer like so

```
  attribute :title do
      TitleSetSerializer.new(object.title).as_json
    end
```

I get 

```
NoMethodError: private method read_attribute_for_serialization called for #<:TitleSet:0x00007f
5d13abe0d8>
Did you mean?  read_attribute_for_validation
from ~/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/active_model_serializers-0.10.10/lib/active_model/se
rializer.rb:397:in read_attribute_for_serialization
```

The reason for this is due to this method in AMS https://github.com/rails-api/active_model_serializers/blob/5ce94fda60b2e1389114ea0a91cd811a8203104e/lib/active_model/serializer.rb#L393-L399

The method in `attr_json` is here which is declared under private
https://github.com/jrochkind/attr_json/blob/cd65f097669e2288c87a356088847397a4efff42/lib/attr_json/model.rb#L289-L291 

Adding the following to my `FieldSet` Class prevents it from breaking

`public :read_attribute_for_serialization`

However  the title attributes all come back as null from the title serializer

```
{
    :primary => {
           :label => nil,
        :subtitle => nil,
        :language => nil
    },
      :other => [
            [0] {
                   :label => nil,
                :subtitle => nil,
                :language => nil
            }
     ]
}
```

This is because the attributes hash in `AttrJson::Model` is not a hash with indifferent access

I discovered this after plating around with it in the rails console like so
```
[6] pry(main)> descriptive.title.primary.attributes[:label]
nil
[7] pry(main)> descriptive.title.primary.attributes['label']
"The wintermind"
```
So the solution for the latter issue is just make attributes a `HashWithIndifferentAccess`

**Comment by jrochkind** [comment] 2019-10-15 19:01
Interesting, it's not clear to me what the documented contract API for `read_attribute_for_serialization`, like if it's justified for the `active_model_serializer` gem to make those assumptions... or why it's doing so, I don't even remember from where in AR I copied this method from. 

it's also not clear to me why it's executing that branch of logic, cause I would have thought the [if respond_to?(attr)[(https://github.com/rails-api/active_model_serializers/blob/5ce94fda60b2e1389114ea0a91cd811a8203104e/lib/active_model/serializer.rb#L394) would return true. So I'm not _totally_ sure it's not a bug in AMS, don't really understand what's going on. 

It's ALSO not clear to me the future of AMS, it seems like it's kind of [not getting much more development and they are encouraging alternative?](https://github.com/rails-api/active_model_serializers#alternatives) (Also not clear to me if AMS is an official Rails gem or a third-party thing). 

BUT this is an easy enough change to make in attr_json, so I don't see any reason not to do it if it makes things work better for you, even without understanding what's going on exactly. 

Not sure about testing... if the intent is supporting `active_model_serializers`, it would be nice to test against it... but I am not thrilled about adding the dependency just for the purpose of a test. Although I guess it could be a dev/test dependency rather than production dependency. 

Not sure if all that complexity with various serializers and models and inheritance is necessary to reproduce the failing test, or if a simpler case would do it. 

Thoughts? Interested in preparing a PR @bbarberBPL ?

**Comment by jrochkind** [comment] 2019-10-15 19:04
@bbarberBPL okay, searching for `read_attribute_for_serialization` in the Rails repo... it's private in _rails_ ActiveModel where I copied it from!

https://github.com/rails/rails/blob/064338998fbe5374b7757e37065f2717a1fbfecd/activemodel/lib/active_model/serialization.rb#L166

So that's why I made it private. 

So this whole thing makes even less sense to me, and it kind of seems like it might be a bug in AMS. 

But I guess I still don't mind making the relatively simple change in attr_json if it makes things work better with AMS, even though AMS seems to be kind of approacching abandonware status (which is also a reason even if it is a bug/mis-design in AMS, it seems unlikely anyone's gonna fix it...)

**Comment by jrochkind** [comment] 2019-10-15 19:07
On the other hand... I wonder if you just want to override `read_attribute_for_serialization` in your own already existing common `FieldSet` class. Cause the HashWithIndifferentAccess requirement seems weird to me too. What I linked to above is instructions from ActiveModel saying you should override the (private) `read_attribute_for_serialization`  "should you retrieve the value for a given attribute differently", which I think is exactly what I've done!

But also I guess it's no big deal, I dunno! Kind of confused.

**Comment by bbarberBPL** [comment] 2019-10-15 19:24
I would say leave the read attributes for serialization private and maybe make note of it your documentation for the the section talking about AttrJson::Model if you are using AMS.  If its going to be abandoned its not worth the extra effort.

As for the attributes part I would change 
https://github.com/jrochkind/attr_json/blob/cd65f097669e2288c87a356088847397a4efff42/lib/attr_json/model.rb#L176-L178

To

```
    def attributes
      @attributes ||= {}.with_indifferent_access
    end
OR

    def attributes
      @attributes ||= HashWithIndifferentAccess.new
    end
```

This way if there is a third party gem that is accessing attributes hash  for a `AttrJson::Model` with a `symbol` key name it will get the correct value. Currently values int the attributes hash are only accessible with a `string` key.  I can do the PR if you prefer.

**Comment by jrochkind** [comment] 2019-10-15 21:00
Hmm, thanks for input. This is kind of a pickle to someone (me) trying to be perfectionist with it!

Using "indifferent" hashes has some performance penalty, and can actually be _really confusing_  too. And it's not clear to me that if/why attributes _should_ return an indifferent hash. 

Rails serialized json is _not_ generally indiffernet, and is attr_json is not generally indifferent. If you make a standard jsonb column with Rails, it is _not_ string/symbol indifferent I don't think, and in fact allows access only with string keys -- my inclination was to leave attr_json consistent, and I'm still cautious about doing different. 

I'm wondering if it's really AMS that is buggy, somehow, although I can't say how. Maybe less buggy than not designed to handle serialized hash attributes, or something. 

Hmm. I don't like it any of the ways.

**Comment by bbarberBPL** [comment] 2019-10-16 13:32
I think you are correct that it is an issue with AMS in general. I found a way to work around this by removing the `TitleSerializer` and `TitleSetSerializer` completely by just doing this in the `DescriptiveSerializer`

```
  attribute :title do
      object.title.as_json
    end
```
This actually works perfectly. The only drawback is if I want to, for a hypothetical reason, exclude or include fields based on the `current_user` context I have to manually do that for each jsonb attribute rather than at the serializer level. This is fine though because you have convinced me to seek an alternative to AMS. I would however make note of the patch for `read_attributes_for_serialization` and maybe a warning about using this gem with AMS in general in your docs.  Thanks for your help with this.

**Comment by bbarberBPL** [comment] 2019-10-16 15:43
Actually it doesn't, Even if i declare the attribute as a string. This is it looks IN the JSON.

```"title" => #<Curator::Descriptives::TitleSet:0x00007f071d4efce8 @attributes={"oth
er"=>[#<Curator::Descriptives::Title:0x00007f071d4ef9c8 @attributes={"type"=>"alternative", "label"=>"The man who woul
d be king", "display"=>"Below map:"}>, #<Curator::Descriptives::Title:0x00007f071d4ef338 @attributes={"type"=>"uniform
", "label"=>"Bible", "id_from_auth"=>"n00020514", "authority_code"=>"naf"}>], "primary"=>#<Curator::Descriptives::Titl
e:0x00007f071d4ee938 @attributes={"label"=>"The wintermind", "usage"=>"primary", "display"=>"primary", "language"=>"en
g", "subtitle"=>"William Bonk and American letters", "supplied"=>true, "part_name"=>"Being the third book", "part_numb
er"=>"Vol. 1", "id_from_auth"=>"n00020514", "authority_code"=>"naf"}>}>,```

Seems if you're using a `include AttrJson::Model` to reference/nest attributes on a  `jsonb` column It doesn't invoke `as_json` to any of those classes when called from the top level class. In this case the top level class is the `Descriptive` class that has a `jsonb` column called `title_json`. Here's how its declared 
```
  class Metastreams::Descriptive < ApplicationRecord
     include AttrJson::Record
    include AttrJson::Record::QueryScopes
    include AttrJson::Record::Dirty
    include AttrJson::NestedAttributes
    ...
     attr_json :title, TitleSet.to_type, container_attribute: :title_json
```
Another thing I noticed is **without** using AMS if you have a `jsonb` column backed by an `AttrJson::Model` and you call `as_json` on the object  without the it serializes the same way  

Here is an example of the descriptive object just calling as_json on itself

[descriptive.txt](https://github.com/jrochkind/attr_json/files/3735139/descriptive.txt)

For Reference [Here](https://github.com/boston-library/curator/blob/master/db/migrate/20190919202311_create_curator_metastreams_descriptives.rb) is the migration of the descriptive class,

The class itself, https://github.com/boston-library/curator/blob/aa115549070e79ab70e70d60c84c517bff92b507/app/models/curator/metastreams/descriptive.rb#L19

And The Various `FieldSets` I made for the `jsonb` columns in the model

https://github.com/boston-library/curator/tree/master/lib/curator/descriptives/field_sets

**Comment by jrochkind** [comment] 2019-10-28 16:14
OK, this is still very confusing for me!

But the `read_attribute_for_serialization` method is consistent with how it looks for an ActiveRecord model -- private, and returning a Hash wtih string keys (that is NOT `WithIndiffernetAccess`). 

So I'm inclined to leave the `AttrJson::Model` implementation consistent. And to suspect there is actually a bug of some kind in `active_model_serializers` -- which looks like it _might_ be abandoned, it's maintenance status is unclear to me. 

So I'm going to close this for now! Thanks for trying, using, and reporting issues with attr_json, I appreciate it, don't hestitate to do so again!

**Closed by jrochkind** 2019-10-28 16:14 UTC
